# Generated by Django 3.2.8 on 2021-10-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_taken', models.DateTimeField()),
                ('descriptions', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.location')),
            ],
        ),
    ]
