# Generated by Django 3.2.8 on 2021-10-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
