# Generated by Django 3.2.8 on 2021-10-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateField(),
        ),
    ]
