# Generated by Django 3.2.8 on 2021-10-11 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_alter_image_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
